services:
  wnioskodawca-galaretki:
    image: depermitto/wnioskodawca-galaretki:latest
    container_name: wnioskodawca-galaretki
    volumes:
      - ./data:/app/data
    env_file: .env
    # environment:
      # - TOKEN=MY-DISCORD-BOT-TOKEn
    restart: unless-stopped
