services:
  wnioskodawca-galaretki:
    build: .
    container_name: wnioskodawca-galaretki
    image: wnioskodawca-galaretki:0.1.1
    volumes:
      - ./data:/app/data
    env_file: .env
    # environment:
      # - TOKEN=MY-DISCORD-BOT-TOKEn
    restart: unless-stopped
